from __future__ import annotations

from typing import Protocol

from app.models import ONUCLIInfo, ONUCustomerInfo, ONUDebugInfo, ONUInfoPerBoard, ONUQuery, ONUPortQuery


class VendorProvider(Protocol):
    @property
    def vendor_tags(self) -> tuple[str, ...]: ...

    @property
    def default_cli_fallback_access(self) -> str: ...

    async def get_onu(self, query: ONUQuery) -> ONUCustomerInfo: ...

    async def get_onup(self, query: ONUPortQuery) -> ONUCustomerInfo: ...

    async def get_onu_debug(self, query: ONUPortQuery) -> ONUDebugInfo: ...

    async def get_onus(self, olt_ip: str, port: str) -> list[ONUInfoPerBoard]: ...

    async def get_onus_new(self, olt_ip: str, port: str) -> list[ONUInfoPerBoard]: ...

    async def get_onu_cli(self, query: ONUQuery, access: str) -> ONUCLIInfo: ...

    async def get_onup_cli(self, query: ONUPortQuery, access: str) -> ONUCLIInfo: ...
